# Created by Jekyll Writer
title: Dungkit
header-img: img/facebook.jpg
tagline: cn
description: Dungkit|Think Different
baseurl: ''
url: 'http://dungkit.github.io'
owner:
  name: dungkit
  email: dungkit@163.com
  bio: ''
gavatar: 'http://dreamofbook.qiniudn.com/Az..png'
favicon: img/favicon.png
douban_username: null
twitter_username: null
github_username: dungkit
weibo_username: dungkit
facebook_username: null
zhihu_username: dungkit
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
timezone: Asia/Shanghai
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      author: dungkit
      header-img: img/facebook.jpg
comments:
  provider: duoshuo
  duoshuo:
    short_name: dungkit
  disqus:
    short_name: dungkit
google_analytics: null
google_verify: null
bing_verify: null
theme: jekyll-theme-cayman
